export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export const SET_UP_CANVAS_SIZE = 'SET_UP_CANVAS_SIZE';
export const MAKE_VERTEX = 'MAKE_VERTEX';
export const MAKE_FACE = 'MAKE_FACE';
export const EDIT_MODE_TOGGLE = 'EDIT_MODE_TOGGLE';
export const AUTO_POPULATE = 'AUTO_POPULATE';
export const SET_BACKGROUND_POLY = 'SET_BACKGROUND_POLY';
export const DOWNLOAD_FLATTEN_IMG = 'DOWNLOAD_FLATTEN_IMG';
